/* توصيل العاشر - التطبيق الرئيسي */
(function(){
'use strict';
let currentUser=null,currentOrderId=null,pickupMap=null,dropoffMap=null,trackMap=null,adminMap=null,pickupMarker=null,dropoffMarker=null;
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=d=>d?new Date(d).toLocaleString('ar-EG'):''; const money=n=>Number(n||0).toFixed(2);
function toast(msg,type='success'){const e=$('toast');e.textContent=msg;e.className='toast '+type;clearTimeout(window._toast);window._toast=setTimeout(()=>e.className='toast hidden',3000)}
function modal(title,body,footer=''){ $('modal-title').textContent=title;$('modal-body').innerHTML=body;$('modal-footer').innerHTML=footer;$('modal').classList.remove('hidden'); }
function closeModal(){$('modal').classList.add('hidden')}
function showScreen(role){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(role+'-screen')?.classList.add('active');}
function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(page)?.classList.add('active');document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const t=$(page+'-title');if(t)$('admin-page-title').textContent=t.textContent||''; if(page==='admin-map')setTimeout(initAdminMap,100); if(page==='admin-database')setTimeout(renderAdminDatabase,50); if(page==='client-create'){setTimeout(initOrderMaps,100);populateZoneSelect();} if(page==='client-track')setTimeout(renderTrack,100); if(page==='client-profile')renderClientProfile(); if(page==='client-notifications')renderNotifications(); if(page==='courier-profile')renderCourierProfile(); if(page==='admin-zones')renderAdminZones(); if(page==='client-ranking')renderRanking(); if(page==='admin-ranking')renderAdminRanking();}
async function populateZoneSelect(){const zones=await DB.all('zones');const sel=$('order-zone');if(sel&&!sel.dataset.filled){sel.innerHTML=zones.map(z=>`<option value="${z.id}">${esc(z.name)}</option>`).join('');sel.dataset.filled='1'}}
async function refresh(){if(!currentUser)return; if(currentUser.role==='admin')await renderAdmin(); if(currentUser.role==='client')await renderClient(); if(currentUser.role==='courier')await renderCourier();}
async function restoreSession(){
 const sid=localStorage.getItem('delivery_session'); if(!sid) return false;
 try{
  const session=await DB.get('sessions',sid);
  if(!session || new Date(session.expiresAt).getTime()<Date.now()){localStorage.removeItem('delivery_session');return false;}
  const u=await DB.get('users',session.userId);
  if(!u || u.status!=='active'){localStorage.removeItem('delivery_session');return false;}
  currentUser={...u,passwordHash:undefined,sessionId:sid};
  showScreen(currentUser.role); await refresh(); await setupRealtime();
  return true;
 }catch(e){localStorage.removeItem('delivery_session');return false;}
}
async function init(){
  wireSupportUI();
 try{
  const withTimeout=(p,ms)=>Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error('التطبيق ماقدرش يتصل بقاعدة البيانات خلال '+(ms/1000)+' ثواني. تأكد إن فيه إنترنت وإن إعدادات Firebase داخل data.js صحيحة وإن الرابط مفتوح من سيرفر (مش بفتح الملف مباشرة من جهازك).')),ms))]);
  await withTimeout(DB.open(),10000);
  await withTimeout(DB.seed(),10000);
 }
 catch(e){
  const s=$('splash'); if(s)s.style.display='none'; $('app')?.classList.remove('hidden');
  document.body.innerHTML='<div style="padding:2rem;text-align:center;font-family:sans-serif;direction:rtl"><h2>التطبيق مش متصل بقاعدة البيانات</h2><p>'+esc(e.message)+'</p><p>راجع إعدادات Firebase داخل data.js وتأكد من Firestore Rules.</p></div>';
  return;
 }
 $('modal-close')?.addEventListener('click',closeModal); $('modal')?.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
 document.querySelectorAll('[data-page]').forEach(e=>e.addEventListener('click',ev=>{ev.preventDefault();go(e.dataset.page);document.querySelector('.sidebar')?.classList.remove('open')}));
 $('sidebar-toggle')?.addEventListener('click',()=>{document.querySelector('.sidebar')?.classList.toggle('open')});
 $('client-notif-btn')?.addEventListener('click',()=>go('client-notifications'));
 $('client-menu-btn')?.addEventListener('click',()=>go('client-profile'));
 document.addEventListener('click',ev=>{const sb=document.querySelector('.sidebar');if(sb&&sb.classList.contains('open')&&!sb.contains(ev.target)&&ev.target.id!=='sidebar-toggle'&&!ev.target.closest('#sidebar-toggle'))sb.classList.remove('open')});
 document.querySelectorAll('.auth-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.auth-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.auth-form').forEach(x=>x.classList.remove('active'));$('login-form').classList.toggle('active',b.dataset.tab==='login');$('register-form').classList.toggle('active',b.dataset.tab==='register')}));
 $('login-form').addEventListener('submit',doLogin);$('register-form').addEventListener('submit',doRegister);$('admin-logout').addEventListener('click',logout);
 $('btn-create-order')?.addEventListener('click',()=>go('client-create'));$('btn-calc-order')?.addEventListener('click',calcOrder);$('create-order-form')?.addEventListener('submit',createOrder);$('courier-online-toggle')?.addEventListener('change',toggleCourier);
 $('admin-order-search')?.addEventListener('input',renderAdminOrders);$('admin-order-filter')?.addEventListener('change',renderAdminOrders);$('admin-db-collection')?.addEventListener('change',renderAdminDatabase);$('admin-db-search')?.addEventListener('input',renderAdminDatabase);$('admin-client-search')?.addEventListener('input',renderAdminClients);$('admin-courier-search')?.addEventListener('input',renderAdminCouriers);$('admin-courier-status')?.addEventListener('change',renderAdminCouriers);
 document.querySelectorAll('#client-orders .tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#client-orders .tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderClientOrdersList(b.dataset.filter)}));
 await restoreSession();
 setTimeout(()=>{const s=$('splash');if(s)s.style.display='none';$('app')?.classList.remove('hidden')},400);
}
async function doLogin(e){e.preventDefault();try{currentUser=await DB.login($('login-phone').value,$('login-password').value,$('login-role').value);localStorage.setItem('delivery_session',currentUser.sessionId);showScreen(currentUser.role);await refresh();await setupRealtime();toast('تم تسجيل الدخول');}catch(err){toast(err.message,'error')}}
async function doRegister(e){e.preventDefault();try{const role=$('reg-role').value;await DB.createUser({name:$('reg-name').value,phone:$('reg-phone').value,password:$('reg-password').value,role});toast('تم إنشاء الحساب ويمكنك تسجيل الدخول');e.target.reset();document.querySelector('[data-tab="login"]').click()}catch(err){toast(err.message,'error')}}
function logout(){try{DB.touchPresence(currentUser.id,false);if(currentUser?.role==='admin')DB.put('support_presence',{id:currentUser.id,role:'admin',online:false,callOpen:false,updatedAt:DB.now()});DB.stopAllListeners()}catch(e){}stopRealtime();currentUser=null;localStorage.removeItem('delivery_session');showScreen('auth');toast('تم تسجيل الخروج')}
async function renderAdmin(){
 const users=await DB.all('users'),orders=await DB.all('orders');
 $('admin-total-clients').textContent=users.filter(x=>x.role==='client').length;$('admin-total-couriers').textContent=users.filter(x=>x.role==='courier').length;
 $('admin-active-orders').textContent=orders.filter(x=>['pending','searching','accepted'].includes(x.status)).length;$('admin-completed-orders').textContent=orders.filter(x=>x.status==='completed').length;$('admin-cancelled-orders').textContent=orders.filter(x=>x.status==='cancelled').length;$('admin-total-revenue').textContent=money(orders.filter(x=>x.status==='completed').reduce((a,x)=>a+Number(x.cost||0),0));
 await renderAdminOrders();await renderAdminClients();await renderAdminCouriers();
 const today=new Date().toISOString().slice(0,10);const rows=orders.filter(x=>x.createdAt?.slice(0,10)===today);$('admin-today-orders').innerHTML=orderTable(rows,true)||empty('لا توجد طلبات اليوم');
}
const statusAr={pending:'بانتظار الموافقة',searching:'جاري البحث عن مندوب',accepted:'تم تعيين مندوب',picked_up:'المندوب في الطريق للتسليم',completed:'مكتمل',cancelled:'ملغي'};
function empty(t){return `<div class="empty-state"><i class="fas fa-inbox"></i><p>${esc(t)}</p></div>`}
let ZONES_CACHE=[];
async function loadZones(){ZONES_CACHE=await DB.all('zones');return ZONES_CACHE;}
function zoneName(id){return (ZONES_CACHE.find(z=>z.id===id)||{}).name||'بدون منطقة'}
function orderTable(rows,compact=false){if(!rows.length)return '';return `<table><thead><tr><th>الطلب</th><th>العميل</th><th>الحالة</th><th>القيمة</th><th>التاريخ</th><th></th></tr></thead><tbody>${rows.map(o=>`<tr><td>#${esc(o.id.slice(-8))}</td><td>${esc(o.clientName||'-')}</td><td>${statusAr[o.status]||o.status}</td><td>${money(o.cost)} ج.م</td><td>${fmtDate(o.createdAt)}</td><td><button class="btn btn-sm btn-primary" onclick="window.adminOrder('${o.id}')">تفاصيل</button></td></tr>`).join('')}</tbody></table>`}
async function renderAdminOrders(){const all=await DB.all('orders'),q=($('admin-order-search')?.value||'').trim().toLowerCase(),f=$('admin-order-filter')?.value||'all';let rows=all.filter(o=>(f==='all'||o.status===f)&&(!q||String(o.id).toLowerCase().includes(q)||String(o.clientName).toLowerCase().includes(q))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));$('admin-orders-table').innerHTML=orderTable(rows)||empty('لا توجد طلبات')}
async function renderAdminClients(){const users=await DB.all('users'),q=($('admin-client-search')?.value||'').toLowerCase();const rows=users.filter(x=>x.role==='client'&&(!q||x.name.toLowerCase().includes(q)||x.phone.includes(q)));$('admin-clients-table').innerHTML=rows.length?`<table><thead><tr><th>الاسم</th><th>الهاتف</th><th>الحالة</th><th>التاريخ</th><th></th></tr></thead><tbody>${rows.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.phone)}</td><td>${u.status==='active'?'فعال':'موقوف'}</td><td>${fmtDate(u.createdAt)}</td><td><button class="btn btn-sm btn-outline" onclick="window.toggleUser('${u.id}')">${u.status==='active'?'إيقاف':'تفعيل'}</button></td></tr>`).join('')}</tbody></table>`:empty('لا يوجد عملاء')}
async function renderAdminCouriers(){const users=await DB.all('users'),zones=await loadZones(),q=($('admin-courier-search')?.value||'').toLowerCase(),f=$('admin-courier-status')?.value||'all';const rows=users.filter(x=>x.role==='courier'&&(!q||x.name.toLowerCase().includes(q)||x.phone.includes(q))&&(f==='all'||(f==='online'?x.online:!x.online)));$('admin-couriers-table').innerHTML=rows.length?`<table><thead><tr><th>الاسم</th><th>الهاتف</th><th>المنطقة</th><th>الاتصال</th><th>التقييم</th><th>المنجز</th><th></th></tr></thead><tbody>${rows.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.phone)}</td><td><select onchange="window.setCourierZone('${u.id}',this.value)"><option value="">بدون منطقة</option>${zones.map(z=>`<option value="${z.id}" ${u.zoneId===z.id?'selected':''}>${esc(z.name)}</option>`).join('')}</select></td><td>${u.online?'متصل':'غير متصل'}</td><td>${u.rating||5}</td><td>${u.completedOrders||0}</td><td><button class="btn btn-sm btn-outline" onclick="window.toggleUser('${u.id}')">${u.status==='active'?'إيقاف':'تفعيل'}</button></td></tr>`).join('')}</tbody></table>`:empty('لا يوجد مندوبون')}
window.setCourierZone=async(id,zoneId)=>{try{await DB.updateUser(id,{zoneId:zoneId||null},currentUser.id);toast('تم تحديث منطقة المندوب')}catch(e){toast(e.message,'error')}};
async function renderAdminZones(){const zones=await DB.all('zones'),users=await DB.all('users');$('admin-zones-table').innerHTML=zones.length?`<table><thead><tr><th>المنطقة</th><th>عدد المندوبين</th><th></th></tr></thead><tbody>${zones.map(z=>`<tr><td>${esc(z.name)}</td><td>${users.filter(u=>u.role==='courier'&&u.zoneId===z.id).length}</td><td><button class="btn btn-sm btn-outline" onclick="window.zoneModal('${z.id}')">تعديل</button> <button class="btn btn-sm btn-danger" onclick="window.deleteZone('${z.id}')">حذف</button></td></tr>`).join('')}</tbody></table>`:empty('لا توجد مناطق بعد')}
window.zoneModal=async(id)=>{const z=id?await DB.get('zones',id):null;modal(z?'تعديل المنطقة':'إضافة منطقة جديدة',`<div class="form-group"><label>اسم المنطقة</label><input id="zone-name" value="${z?esc(z.name):''}" placeholder="مثال: الحي الحادي عشر"></div>`,`<button class="btn btn-outline" onclick="closeModal()">إلغاء</button><button class="btn btn-primary" onclick="window.saveZone('${id||''}')">حفظ</button>`)};
window.saveZone=async(id)=>{const name=$('zone-name').value.trim();if(!name)return toast('اكتب اسم المنطقة','error');try{if(id){const z=await DB.get('zones',id);z.name=name;await DB.put('zones',z)}else{await DB.put('zones',{id:DB.uid('zone'),name,createdAt:DB.now()})}closeModal();toast('تم الحفظ');renderAdminZones()}catch(e){toast(e.message,'error')}};
window.deleteZone=async(id)=>{if(!confirm('حذف هذه المنطقة؟ سيتم إلغاء تعيينها من أي مندوب.'))return;try{const users=(await DB.all('users')).filter(u=>u.zoneId===id);for(const u of users)await DB.updateUser(u.id,{zoneId:null},currentUser.id);await DB.del('zones',id);toast('تم الحذف');renderAdminZones()}catch(e){toast(e.message,'error')}};
window.toggleUser=async id=>{const u=await DB.get('users',id);await DB.updateUser(id,{status:u.status==='active'?'suspended':'active'},currentUser.id);toast('تم تحديث حالة الحساب');refresh()};
window.adminOrder=async id=>{currentOrderId=id;const o=await DB.get('orders',id);if(!o)return;const couriers=(await DB.all('users')).filter(x=>x.role==='courier'&&x.status==='active');const proofHtml=o.proofPhoto?`<p>صورة إثبات التسليم:</p><img src="${o.proofPhoto}" class="proof-img">`:'';$('admin-order-details-content').innerHTML=`<div class="order-card"><h3>طلب #${esc(o.id.slice(-8))}</h3><p>العميل: ${esc(o.clientName)}</p><p>المستلم: ${esc(o.receiverName)} - ${esc(o.receiverPhone)}</p><p>الاستلام: ${esc(o.pickupAddress)}</p><p>التسليم: ${esc(o.dropoffAddress)}</p>${o.zoneName?`<p>المنطقة: ${esc(o.zoneName)}</p>`:''}<p>القيمة: <b>${money(o.cost)} ج.م</b></p><p>الحالة: ${statusAr[o.status]}</p>${proofHtml}<div class="form-row"><button class="btn btn-success" onclick="window.approveOrder('${o.id}')">قبول الطلب</button><button class="btn btn-danger" onclick="window.cancelOrder('${o.id}')">رفض/إلغاء</button></div><hr><h4>تعيين مندوب</h4><select id="assign-courier"><option value="">اختر مندوباً</option>${couriers.map(c=>`<option value="${c.id}" ${o.courierId===c.id?'selected':''}>${esc(c.name)} - ${esc(c.phone)}</option>`).join('')}</select><button class="btn btn-primary" onclick="window.assignCourier('${o.id}')">تعيين</button></div>`;go('admin-order-details')};
window.approveOrder=async id=>{const o=await DB.get('orders',id);o.status='searching';o.updatedAt=DB.now();await DB.put('orders',o);await DB.notify(o.clientId,'تم قبول الطلب','تم قبول طلبك وبدأ البحث عن مندوب','success',{orderId:id});await DB.log(currentUser.id,'approve_order','قبول طلب',{orderId:id});toast('تم قبول الطلب');window.adminOrder(id)};
window.cancelOrder=async id=>{const o=await DB.get('orders',id);o.status='cancelled';o.updatedAt=DB.now();await DB.put('orders',o);await DB.notify(o.clientId,'تم إلغاء الطلب','تم إلغاء طلبك من الإدارة','warning',{orderId:id});await DB.log(currentUser.id,'cancel_order','إلغاء طلب',{orderId:id});toast('تم إلغاء الطلب');window.adminOrder(id)};
window.assignCourier=async id=>{const cid=$('assign-courier').value;if(!cid)return toast('اختر مندوباً','error');const o=await DB.get('orders',id);const c=await DB.get('users',cid);o.courierId=cid;o.courierName=c.name;o.status='accepted';o.updatedAt=DB.now();await DB.put('orders',o);await DB.notify(cid,'طلب جديد','تم تعيين طلب جديد لك',{orderId:id});await DB.notify(o.clientId,'تم تعيين مندوب','تم تعيين '+c.name+' لطلبك','info',{orderId:id});await DB.log(currentUser.id,'assign_courier','تعيين مندوب',{orderId:id,courierId:cid});toast('تم تعيين المندوب');window.adminOrder(id)};
function adminManagerUI(){modal('إنشاء حساب مدير',`<div class="form-group"><label>الاسم</label><input id="new-admin-name"></div><div class="form-group"><label>رقم الهاتف</label><input id="new-admin-phone" type="tel"></div><div class="form-group"><label>كلمة المرور</label><input id="new-admin-pass" type="password"></div><div class="form-group"><label>الحالة</label><select id="new-admin-status"><option value="active">فعال</option><option value="suspended">موقوف</option></select></div>`,`<button class="btn btn-outline" onclick="closeModal()">إلغاء</button><button class="btn btn-primary" onclick="window.createAdmin()">إنشاء</button>`)}
window.createAdmin=async()=>{try{const u=await DB.createUser({name:$('new-admin-name').value,phone:$('new-admin-phone').value,password:$('new-admin-pass').value,role:'admin',status:$('new-admin-status').value},currentUser.id);await DB.notify(u.id,'حساب المدير','تم إنشاء حساب مدير لك','success');closeModal();toast('تم إنشاء حساب المدير');renderAdminManagers()}catch(e){toast(e.message,'error')}};
async function renderAdminManagers(){const users=(await DB.all('users')).filter(x=>x.role==='admin');let box=$('admin-managers-table');if(!box)return;box.innerHTML=`<table><thead><tr><th>الاسم</th><th>الهاتف</th><th>الحالة</th><th>الإنشاء</th><th>إجراءات</th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.phone)}</td><td>${u.status==='active'?'فعال':'موقوف'}</td><td>${fmtDate(u.createdAt)}</td><td><button class="btn btn-sm btn-outline" onclick="window.editAdmin('${u.id}')">تعديل</button> <button class="btn btn-sm btn-danger" onclick="window.removeAdmin('${u.id}')">حذف</button></td></tr>`).join('')}</tbody></table>`}
window.editAdmin=async id=>{const u=await DB.get('users',id);modal('تعديل المدير',`<div class="form-group"><label>الاسم</label><input id="ea-name" value="${esc(u.name)}"></div><div class="form-group"><label>الهاتف</label><input id="ea-phone" value="${esc(u.phone)}"></div><div class="form-group"><label>كلمة مرور جديدة (اختياري)</label><input id="ea-pass" type="password"></div><div class="form-group"><label>الحالة</label><select id="ea-status"><option value="active" ${u.status==='active'?'selected':''}>فعال</option><option value="suspended" ${u.status!=='active'?'selected':''}>موقوف</option></select></div>`,`<button class="btn btn-outline" onclick="closeModal()">إلغاء</button><button class="btn btn-primary" onclick="window.saveAdmin('${id}')">حفظ</button>`)};
window.saveAdmin=async id=>{try{const p={name:$('ea-name').value,phone:$('ea-phone').value,status:$('ea-status').value};if($('ea-pass').value)p.password=$('ea-pass').value;await DB.updateUser(id,p,currentUser.id);closeModal();toast('تم الحفظ');renderAdminManagers()}catch(e){toast(e.message,'error')}};
window.removeAdmin=async id=>{if(!confirm('حذف حساب المدير؟'))return;try{await DB.deleteUser(id,currentUser.id);toast('تم الحذف');renderAdminManagers()}catch(e){toast(e.message,'error')}};
async function renderClient(){await loadZones();const orders=(await DB.all('orders')).filter(x=>x.clientId===currentUser.id);$('client-name').textContent=currentUser.name;if(currentUser.avatar)$('client-avatar').src=currentUser.avatar;$('client-completed').textContent=orders.filter(x=>x.status==='completed').length;$('client-active').textContent=orders.filter(x=>!['completed','cancelled'].includes(x.status)).length;$('client-cancelled').textContent=orders.filter(x=>x.status==='cancelled').length;$('client-recent-orders').innerHTML=orderCards(orders.slice(-5).reverse(),'client');const cur=orders.find(x=>!['completed','cancelled'].includes(x.status));$('client-current-order').innerHTML=cur?orderCard(cur,'client'):empty('لا يوجد طلب جاري حالياً');window._clientOrdersAll=orders.reverse();renderClientOrdersList('all');await renderNotifications();await renderRanking()}
async function renderRanking(){
  const now=new Date(), month=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;
  const orders=await DB.all('orders'), users=await DB.all('users');
  const clients=users.filter(u=>u.role==='client'&&u.status==='active');
  const stats=clients.map(u=>{const os=orders.filter(o=>o.clientId===u.id&&o.status==='completed'&&String(o.completedAt||o.updatedAt||o.createdAt).slice(0,7)===month);return {...u,monthlyOrders:os.length,monthlySpent:os.reduce((s,o)=>s+Number(o.cost||0),0)}}).sort((a,b)=>b.monthlyOrders-a.monthlyOrders||b.monthlySpent-a.monthlySpent);
  const top=stats.slice(0,10); const mine=stats.find(x=>x.id===currentUser?.id);
  const rewards=await DB.all('ranking_rewards');
  const rewardByUser={}; rewards.filter(x=>x.month===month).forEach(x=>rewardByUser[x.userId]=x);
  const box=$('client-ranking-list'); if(box) box.innerHTML=top.length?top.map((u,i)=>`<div class="ranking-row ${u.id===currentUser?.id?'me':''}"><div class="rank-medal">${i<3?['🥇','🥈','🥉'][i]:i+1}</div><div class="ranking-avatar"><img src="${u.avatar||'https://ui-avatars.com/api/?name='+encodeURIComponent(u.name)+'&background=0f766e&color=fff'}"></div><div class="ranking-user"><b>${esc(u.name)}</b><small>${u.monthlyOrders} طلب مكتمل · ${money(u.monthlySpent)} ج.م</small></div>${rewardByUser[u.id]?'<span class="reward-badge"><i class="fas fa-gift"></i> تم استلام الهدية</span>':''}</div>`).join(''):empty('لا توجد بيانات لهذا الشهر');
  if($('client-ranking-month'))$('client-ranking-month').textContent=month;
  if($('client-ranking-me'))$('client-ranking-me').innerHTML=mine?`ترتيبك هذا الشهر: <b>#${stats.findIndex(x=>x.id===mine.id)+1}</b> · ${mine.monthlyOrders} طلب مكتمل`:'ابدأ باستخدام التطبيق للدخول في الترتيب';
}
async function renderAdminRanking(){
  const now=new Date(), month=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;
  const orders=await DB.all('orders'), users=await DB.all('users'), rewards=await DB.all('ranking_rewards');
  const clients=users.filter(u=>u.role==='client');
  const rows=clients.map(u=>{const os=orders.filter(o=>o.clientId===u.id&&o.status==='completed'&&String(o.completedAt||o.updatedAt||o.createdAt).slice(0,7)===month);return {u,count:os.length,spent:os.reduce((s,o)=>s+Number(o.cost||0),0)}}).filter(x=>x.count>0).sort((a,b)=>b.count-a.count||b.spent-a.spent);
  const box=$('admin-ranking-table'); if(!box)return;
  box.innerHTML=rows.length?`<table><thead><tr><th>#</th><th>العميل</th><th>الطلبات المكتملة</th><th>الإنفاق</th><th>الهدية</th><th>إجراء</th></tr></thead><tbody>${rows.map((x,i)=>{const r=rewards.find(r=>r.month===month&&r.userId===x.u.id);return `<tr><td>${i+1}</td><td><b>${esc(x.u.name)}</b><br><small>${esc(x.u.phone)}</small></td><td>${x.count}</td><td>${money(x.spent)} ج.م</td><td>${r?`<span class="reward-badge"><i class="fas fa-gift"></i> ${esc(r.reward||'هدية شهرية')}</span>`:'—'}</td><td><button class="btn btn-sm ${r?'btn-outline':'btn-primary'}" onclick="window.grantRankingReward('${x.u.id}','${month}')" ${r?'disabled':''}><i class="fas fa-gift"></i> ${r?'تم التسجيل':'منح الهدية'}</button></td></tr>`}).join('')}</tbody></table>`:empty('لا توجد بيانات استخدام مكتملة لهذا الشهر');
  if($('admin-ranking-month'))$('admin-ranking-month').textContent=month;
}
window.grantRankingReward=async(id,month)=>{const u=await DB.get('users',id);if(!u)return;const reward=prompt('اكتب اسم الهدية الشهرية للعميل:', 'هدية شهرية');if(reward===null)return;const r={id:`${month}_${id}`,month,userId:id,userName:u.name,reward:reward||'هدية شهرية',grantedBy:currentUser.id,createdAt:DB.now()};await DB.put('ranking_rewards',r);await DB.notify(id,'مبروك! 🎁','حصلت على هدية الشهر بسبب نشاطك في التطبيق: '+r.reward,'success',{month,reward:r.reward});await DB.log(currentUser.id,'grant_ranking_reward','منح هدية شهرية',{userId:id,month,reward:r.reward});toast('تم تسجيل الهدية وإرسال إشعار للعميل');renderAdminRanking();};
function renderClientOrdersList(filter){filter=filter||'all';const orders=window._clientOrdersAll||[];const rows=orders.filter(o=>filter==='all'||(filter==='active'&&!['completed','cancelled'].includes(o.status))||o.status===filter);$('client-orders-list').innerHTML=orderCards(rows,'client')}
function orderCard(o,ctx){if(!o||!o.id)return '';ctx=ctx||'client';const handler=ctx==='courier'?`window.courierOpenOrder('${o.id}')`:`window.clientOrder('${o.id}')`;return `<div class="order-card" onclick="${handler}"><b>#${esc(o.id.slice(-8))}</b><span>${statusAr[o.status]||o.status}</span><p>${esc(o.pickupAddress)} ← ${esc(o.dropoffAddress)}</p><strong>${money(o.cost)} ج.م</strong></div>`}
function orderCards(a,ctx){return a&&a.length?a.map(o=>orderCard(o,ctx)).join(''):empty('لا توجد طلبات')}
window.clientOrder=async id=>{currentOrderId=id;const o=await DB.get('orders',id);$('order-id-title').textContent='#'+o.id.slice(-8);let ratingHtml='';if(o.status==='completed'&&o.courierId){ratingHtml=o.rating?`<p><b>تقييمك:</b> ${'★'.repeat(o.rating)}${'☆'.repeat(5-o.rating)}</p>`:`<div class="rate-box"><b>قيّم المندوب:</b><div class="stars">${[1,2,3,4,5].map(n=>`<i class="fas fa-star" onclick="window.rateOrder('${o.id}',${n})"></i>`).join('')}</div></div>`}
const proofHtml=o.proofPhoto?`<p><b>صورة إثبات التسليم:</b></p><img src="${o.proofPhoto}" class="proof-img">`:'';
$('order-details-content').innerHTML=`<div class="order-card"><p><b>الحالة:</b> ${statusAr[o.status]}</p><p><b>الاستلام:</b> ${esc(o.pickupAddress)}</p><p><b>التسليم:</b> ${esc(o.dropoffAddress)}</p>${o.zoneName?`<p><b>المنطقة:</b> ${esc(o.zoneName)}</p>`:''}<p><b>المستلم:</b> ${esc(o.receiverName)} - ${esc(o.receiverPhone)}</p><p><b>المندوب:</b> ${esc(o.courierName||'لم يتم التعيين')}</p><p><b>التكلفة:</b> ${money(o.cost)} ج.م</p>${proofHtml}${ratingHtml}<button class="btn btn-primary" onclick="go('client-track')">تتبع الطلب</button>${!['completed','cancelled'].includes(o.status)?`<button class="btn btn-danger" onclick="window.clientCancel('${o.id}')">إلغاء الطلب</button>`:''}</div>`;go('client-order-details')};
window.rateOrder=async(id,stars)=>{try{const o=await DB.get('orders',id);o.rating=stars;o.updatedAt=DB.now();await DB.put('orders',o);const c=await DB.get('users',o.courierId);if(c){const all=(await DB.all('orders')).filter(x=>x.courierId===o.courierId&&x.rating);const avg=all.reduce((a,x)=>a+x.rating,0)/all.length;c.rating=Math.round(avg*10)/10;c.updatedAt=DB.now();await DB.put('users',c);}toast('شكراً لتقييمك');window.clientOrder(id)}catch(e){toast(e.message,'error')}};
window.clientCancel=async id=>{const o=await DB.get('orders',id);if(o.status==='completed')return; o.status='cancelled';o.updatedAt=DB.now();await DB.put('orders',o);await DB.log(currentUser.id,'client_cancel','إلغاء من العميل',{orderId:id});if(o.courierId)await DB.notify(o.courierId,'إلغاء طلب','تم إلغاء الطلب',{orderId:id});toast('تم إلغاء الطلب');await refresh();go('client-orders')};
async function renderNotifications(){const n=(await DB.all('notifications')).filter(x=>x.userId===currentUser.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));$('client-notif-count').textContent=n.filter(x=>!x.read).length;$('client-notif-list').innerHTML=n.length?n.map(x=>`<div class="notif-item ${x.read?'':'unread'}" onclick="window.readNotif('${x.id}')"><b>${esc(x.title)}</b><p>${esc(x.message)}</p><small>${fmtDate(x.createdAt)}</small></div>`).join(''):empty('لا توجد إشعارات')}
window.readNotif=async id=>{const n=await DB.get('notifications',id);n.read=true;await DB.put('notifications',n);renderNotifications()};
async function renderCourier(){await loadZones();const u=await DB.get('users',currentUser.id);currentUser=u;$('courier-name').textContent=u.name;if(u.avatar)$('courier-avatar').src=u.avatar;$('courier-status-text').textContent=(u.online?'متصل':'غير متصل')+(u.zoneId?' - '+zoneName(u.zoneId):'');$('courier-online-toggle').checked=!!u.online;const orders=await DB.all('orders');const mine=orders.filter(x=>x.courierId===u.id),avail=orders.filter(x=>x.status==='searching'&&!x.courierId&&(!u.zoneId||!x.zoneId||x.zoneId===u.zoneId));$('courier-earnings').textContent=money(u.earnings);$('courier-done').textContent=u.completedOrders||mine.filter(x=>x.status==='completed').length;$('courier-rating').textContent=u.rating||5;const cur=mine.find(x=>['accepted','picked_up'].includes(x.status));$('courier-current-order').innerHTML=cur?orderCard(cur,'courier'):empty('لا يوجد طلب حالياً');$('courier-available-orders').innerHTML=avail.map(o=>`<div class="order-card"><b>#${o.id.slice(-8)}</b><span>${esc(o.zoneName||'')}</span><p>${esc(o.pickupAddress)} ← ${esc(o.dropoffAddress)}</p><strong>${money(o.cost)} ج.م</strong><button class="btn btn-primary" onclick="window.acceptCourierOrder('${o.id}')">قبول الطلب</button></div>`).join('')||empty('لا توجد طلبات متاحة في منطقتك حالياً');$('courier-orders-list').innerHTML=orderCards(mine,'courier')}
window.courierOpenOrder=async id=>{currentOrderId=id;go('courier-execute');await renderCourierExecute()};
async function renderCourierExecute(){const o=await DB.get('orders',currentOrderId);if(!o)return;const box=$('courier-execute-content');
if(o.status==='accepted'){box.innerHTML=`<div class="order-card"><b>#${esc(o.id.slice(-8))}</b><p><b>مكان الاستلام:</b> ${esc(o.pickupAddress)}</p><p><b>الشحنة:</b> ${esc(o.packageDesc||o.packageType)}</p><p><b>ملاحظات:</b> ${esc(o.notes||'-')}</p><button class="btn btn-primary btn-block" onclick="window.pickupOrder('${o.id}')"><i class="fas fa-box"></i> تم استلام الشحنة</button></div>`;}
else if(o.status==='picked_up'){box.innerHTML=`<div class="order-card"><b>#${esc(o.id.slice(-8))}</b><p><b>مكان التسليم:</b> ${esc(o.dropoffAddress)}</p><p><b>المستلم:</b> ${esc(o.receiverName)} - ${esc(o.receiverPhone)}</p><button class="btn btn-success btn-block" onclick="window.openDeliverModal('${o.id}')"><i class="fas fa-check-double"></i> تسليم الطلب</button></div>`;}
else{box.innerHTML=`<div class="order-card"><b>#${esc(o.id.slice(-8))}</b><p>${statusAr[o.status]}</p></div>`;}
}
window.pickupOrder=async id=>{try{const o=await DB.get('orders',id);o.status='picked_up';o.pickedUpAt=DB.now();o.updatedAt=DB.now();await DB.put('orders',o);await DB.notify(o.clientId,'استلام الشحنة','قام المندوب باستلام شحنتك وهو في الطريق للتسليم','info',{orderId:id});await DB.log(currentUser.id,'pickup_order','استلام شحنة',{orderId:id});toast('تم تحديث حالة الطلب');await renderCourierExecute();await refresh()}catch(e){toast(e.message,'error')}};
window.openDeliverModal=id=>{window._proofData=null;modal('تسليم الطلب',`<p>لو المستلم مش موجود ووصّلت الشحنة لحد غيره، ارفع صورة إثبات التسليم (اختياري).</p><div class="form-group"><label>صورة إثبات التسليم</label><input type="file" id="proof-photo" accept="image/*"></div><div id="proof-preview"></div>`,`<button class="btn btn-outline" onclick="closeModal()">إلغاء</button><button class="btn btn-success" onclick="window.confirmDeliver('${id}')">تأكيد التسليم</button>`);$('proof-photo').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{window._proofData=r.result;$('proof-preview').innerHTML=`<img src="${r.result}" class="proof-img">`};r.readAsDataURL(f)})};
window.confirmDeliver=async id=>{try{const o=await DB.get('orders',id);o.status='completed';o.deliveredAt=DB.now();o.updatedAt=DB.now();if(window._proofData)o.proofPhoto=window._proofData;await DB.put('orders',o);const c=await DB.get('users',currentUser.id);c.earnings=(c.earnings||0)+Number(o.cost||0);c.completedOrders=(c.completedOrders||0)+1;c.updatedAt=DB.now();await DB.put('users',c);currentUser=c;await DB.notify(o.clientId,'تم التسليم','تم تسليم طلبك بنجاح، يمكنك تقييم المندوب','success',{orderId:id});await DB.log(currentUser.id,'complete_order','تسليم طلب',{orderId:id});window._proofData=null;closeModal();toast('تم تسليم الطلب بنجاح');go('courier-home');await refresh()}catch(e){toast(e.message,'error')}};
async function renderClientProfile(){const u=await DB.get('users',currentUser.id);$('client-profile-content').innerHTML=`<img src="${u.avatar||'https://ui-avatars.com/api/?name='+encodeURIComponent(u.name)+'&background=0f766e&color=fff'}" class="avatar"><h3>${esc(u.name)}</h3><p><i class="fas fa-phone"></i> ${esc(u.phone)}</p><p><i class="fas fa-location-dot"></i> ${esc(u.address||'لم يتم إضافة عنوان')}</p><p>${esc(u.bio||'لا توجد نبذة تعريفية')}</p><button class="btn btn-outline btn-block" onclick="window.editProfile()"><i class="fas fa-user-edit"></i> تعديل الملف الشخصي</button><button class="btn btn-danger btn-block" onclick="logout()"><i class="fas fa-sign-out-alt"></i> تسجيل الخروج</button>`}
async function renderCourierProfile(){const u=await DB.get('users',currentUser.id);await loadZones();$('courier-profile-content').innerHTML=`<img src="${u.avatar||'https://ui-avatars.com/api/?name='+encodeURIComponent(u.name)+'&background=0369a1&color=fff'}" class="avatar"><h3>${esc(u.name)}</h3><p><i class="fas fa-phone"></i> ${esc(u.phone)}</p><p><i class="fas fa-map-marker-alt"></i> ${esc(zoneName(u.zoneId))}</p><p><i class="fas fa-location-dot"></i> ${esc(u.address||'لم يتم إضافة عنوان')}</p><p><i class="fas fa-motorcycle"></i> ${esc(u.specialty||'لم يتم تحديد التخصص')}</p><p>${esc(u.bio||'لا توجد نبذة تعريفية')}</p><p><i class="fas fa-star text-warning"></i> ${u.rating||5} تقييم - ${u.completedOrders||0} طلب مكتمل</p><button class="btn btn-outline btn-block" onclick="window.editProfile()"><i class="fas fa-user-edit"></i> تعديل الملف الشخصي</button><button class="btn btn-danger btn-block" onclick="logout()"><i class="fas fa-sign-out-alt"></i> تسجيل الخروج</button>`}
window.editProfile=async()=>{const u=await DB.get('users',currentUser.id);const isCourier=u.role==='courier';window._epAvatar=u.avatar||'';modal('تعديل الملف الشخصي',`<div class="form-group"><label>الصورة الشخصية</label><input type="file" id="ep-avatar" accept="image/*"><div id="ep-avatar-preview">${u.avatar?`<img src="${u.avatar}" class="avatar-sm-preview">`:''}</div></div><div class="form-group"><label>الاسم</label><input id="ep-name" value="${esc(u.name)}"></div><div class="form-group"><label>نبذة تعريفية</label><textarea id="ep-bio" rows="2">${esc(u.bio||'')}</textarea></div><div class="form-group"><label>العنوان</label><input id="ep-address" value="${esc(u.address||'')}"></div>${isCourier?`<div class="form-group"><label>التخصص / نوع المركبة</label><input id="ep-specialty" value="${esc(u.specialty||'')}" placeholder="مثال: توصيل موتوسيكل"></div>`:''}`,`<button class="btn btn-outline" onclick="closeModal()">إلغاء</button><button class="btn btn-primary" onclick="window.saveProfile()">حفظ</button>`);$('ep-avatar').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{window._epAvatar=r.result;$('ep-avatar-preview').innerHTML=`<img src="${r.result}" class="avatar-sm-preview">`};r.readAsDataURL(f)})};
window.saveProfile=async()=>{try{const patch={name:$('ep-name').value,bio:$('ep-bio').value,address:$('ep-address').value,avatar:window._epAvatar};const sp=$('ep-specialty');if(sp)patch.specialty=sp.value;const u=await DB.updateUser(currentUser.id,patch,currentUser.id);currentUser=u;closeModal();toast('تم حفظ الملف الشخصي');if(u.role==='client'){$('client-name').textContent=u.name;if(u.avatar)$('client-avatar').src=u.avatar;renderClientProfile()}else{$('courier-name').textContent=u.name;if(u.avatar)$('courier-avatar').src=u.avatar;renderCourierProfile()}}catch(e){toast(e.message,'error')}};
async function toggleCourier(e){const u=await DB.get('users',currentUser.id);u.online=e.target.checked;u.updatedAt=DB.now();await DB.put('users',u);currentUser=u;toast(u.online?'أصبحت متصلاً':'أصبحت غير متصل');renderCourier()}
window.acceptCourierOrder=async id=>{const o=await DB.get('orders',id);if(o.courierId&&o.courierId!==currentUser.id)return toast('الطلب تم أخذه','error');o.courierId=currentUser.id;o.courierName=currentUser.name;o.status='accepted';o.updatedAt=DB.now();await DB.put('orders',o);await DB.notify(o.clientId,'تم قبول الطلب','المندوب '+currentUser.name+' قبل طلبك','success',{orderId:id});await DB.log(currentUser.id,'accept_order','قبول طلب مندوب',{orderId:id});toast('تم قبول الطلب');renderCourier()};
function haversineKm(lat1,lng1,lat2,lng2){const R=6371,toRad=d=>d*Math.PI/180;const dLat=toRad(lat2-lat1),dLng=toRad(lng2-lng1);const s=Math.sin(dLat/2)**2+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(s),Math.sqrt(1-s));}
function calcOrder(){const a=$('pickup-address').value,b=$('dropoff-address').value;if(!a||!b)return toast('أدخل عنواني الاستلام والتسليم','error');
 const pLat=Number($('pickup-lat').value),pLng=Number($('pickup-lng').value),dLat=Number($('dropoff-lat').value),dLng=Number($('dropoff-lng').value);
 let distance;
 if(pLat&&pLng&&dLat&&dLng){distance=Math.max(1,Math.round(haversineKm(pLat,pLng,dLat,dLng)*10)/10);}
 else{distance=5;toast('لم تحدد النقاط على الخريطة، تم استخدام مسافة تقديرية','warning');}
 const cost=20+distance*8;$('sum-distance').textContent=distance+' كم';$('sum-cost').textContent=money(cost)+' ج.م';$('sum-payment').textContent=document.querySelector('input[name=payment]:checked').value==='cash'?'نقداً':'محفظة';$('order-summary').style.display='block';$('btn-confirm-order').disabled=false;window._orderCost=cost;window._orderDistance=distance}
async function createOrder(e){e.preventDefault();if($('btn-confirm-order').disabled)return;const zoneSel=$('order-zone');const zoneId=zoneSel?zoneSel.value:'';const zoneName=zoneSel&&zoneSel.selectedOptions[0]?zoneSel.selectedOptions[0].textContent:'';const o={id:DB.uid('ORD'),clientId:currentUser.id,clientName:currentUser.name,status:'pending',pickupAddress:$('pickup-address').value,pickupLat:Number($('pickup-lat').value||30.2989),pickupLng:Number($('pickup-lng').value||31.7414),dropoffAddress:$('dropoff-address').value,dropoffLat:Number($('dropoff-lat').value||30.31),dropoffLng:Number($('dropoff-lng').value||31.75),zoneId,zoneName,receiverName:$('receiver-name').value,receiverPhone:$('receiver-phone').value,packageType:$('package-type').value,packageDesc:$('package-desc').value,weight:Number($('package-weight').value||1),size:$('package-size').value,notes:$('order-notes').value,payment:document.querySelector('input[name=payment]:checked').value,distance:window._orderDistance||5,cost:window._orderCost||60,createdAt:DB.now(),updatedAt:DB.now()};await DB.put('orders',o);await DB.log(currentUser.id,'create_order','إنشاء طلب',{orderId:o.id});const admins=(await DB.all('users')).filter(x=>x.role==='admin'&&x.status==='active');for(const a of admins)await DB.notify(a.id,'طلب جديد','تم إنشاء طلب جديد #'+o.id.slice(-8),'info',{orderId:o.id});toast('تم إنشاء الطلب');e.target.reset();$('order-summary').style.display='none';$('btn-confirm-order').disabled=true;await refresh();go('client-order-details');window.clientOrder(o.id)}
function initOrderMaps(){if(typeof L==='undefined')return;const center=[30.2989,31.7414];if(!pickupMap){pickupMap=L.map('pickup-map').setView(center,12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(pickupMap);pickupMap.on('click',e=>{if(pickupMarker)pickupMap.removeLayer(pickupMarker);pickupMarker=L.marker(e.latlng).addTo(pickupMap);$('pickup-lat').value=e.latlng.lat;$('pickup-lng').value=e.latlng.lng})}if(!dropoffMap){dropoffMap=L.map('dropoff-map').setView(center,12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(dropoffMap);dropoffMap.on('click',e=>{if(dropoffMarker)dropoffMap.removeLayer(dropoffMarker);dropoffMarker=L.marker(e.latlng).addTo(dropoffMap);$('dropoff-lat').value=e.latlng.lat;$('dropoff-lng').value=e.latlng.lng})}setTimeout(()=>{pickupMap.invalidateSize();dropoffMap.invalidateSize()},200)}
function renderTrack(){if(typeof L==='undefined'||!currentOrderId)return;DB.get('orders',currentOrderId).then(o=>{if(!o)return;if(!trackMap){trackMap=L.map('track-map').setView([o.pickupLat,o.pickupLng],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(trackMap)}L.marker([o.pickupLat,o.pickupLng]).addTo(trackMap).bindPopup('الاستلام');L.marker([o.dropoffLat,o.dropoffLng]).addTo(trackMap).bindPopup('التسليم');$('track-info').innerHTML=`<div class="order-card"><b>الحالة: ${statusAr[o.status]}</b><p>المندوب: ${esc(o.courierName||'لم يتم التعيين')}</p></div>`;setTimeout(()=>trackMap.invalidateSize(),200)})}
const ADMIN_DB_COLLECTIONS={users:'المستخدمون',orders:'الطلبات',zones:'المناطق',settings:'الإعدادات',notifications:'الإشعارات',audit_logs:'سجل العمليات'};
function adminDbValue(v){
  if(v===null||v===undefined)return '';
  if(typeof v==='object')return JSON.stringify(v);
  return String(v);
}
function adminDbPreview(v){
  const s=adminDbValue(v);
  return esc(s.length>110?s.slice(0,110)+'…':s);
}
async function renderAdminDatabase(){
  if(!currentUser||currentUser.role!=='admin')return;
  const col=$('admin-db-collection')?.value||'users';
  const q=($('admin-db-search')?.value||'').trim().toLowerCase();
  const rows=await DB.all(col);
  const filtered=rows.filter(r=>!q||JSON.stringify(r).toLowerCase().includes(q));
  if($('admin-db-count'))$('admin-db-count').textContent=filtered.length+' / '+rows.length;
  const keys=[]; filtered.forEach(r=>Object.keys(r||{}).forEach(k=>{if(!keys.includes(k))keys.push(k)}));
  const visibleKeys=keys.slice(0,5);
  $('admin-database-table').innerHTML=filtered.length?`<table><thead><tr><th>#</th>${visibleKeys.map(k=>`<th>${esc(k)}</th>`).join('')}<th>إجراءات</th></tr></thead><tbody>${filtered.map((r,i)=>{const id=r.id??r.key??('row-'+i);return `<tr><td>${i+1}</td>${visibleKeys.map(k=>`<td title="${esc(adminDbValue(r[k]))}">${adminDbPreview(r[k])||'-'}</td>`).join('')}<td><button class="btn btn-sm btn-outline" onclick="window.adminDbEdit('${esc(String(id))}')">تعديل</button> <button class="btn btn-sm btn-danger" onclick="window.adminDbDelete('${esc(String(id))}')">حذف</button></td></tr>`}).join('')}</tbody></table>`:empty('لا توجد سجلات');
}
function adminDbFindId(row,col){return row&&(row.id??row.key);}
window.adminDbRefresh=()=>renderAdminDatabase();
window.adminDbAdd=()=>{
  if(!currentUser||currentUser.role!=='admin')return;
  const col=$('admin-db-collection').value;
  const id=col==='settings'?'':DB.uid(col.slice(0,3));
  const sample={id:id||undefined};
  if(col==='settings'){delete sample.id;sample.key='app';sample.value={};}
  modal('إضافة سجل — '+(ADMIN_DB_COLLECTIONS[col]||col),`<div class="form-group"><label>JSON</label><textarea id="admin-db-json" rows="16" style="direction:ltr;text-align:left;font-family:monospace">${esc(JSON.stringify(sample,null,2))}</textarea><small>أدخل كائن JSON صالح. في الإعدادات استخدم الحقل key بدل id.</small></div>`,`<button class="btn btn-outline" onclick="closeModal()">إلغاء</button><button class="btn btn-primary" onclick="window.adminDbSave(null)">حفظ في قاعدة البيانات</button>`);
};
window.adminDbEdit=async id=>{
  if(!currentUser||currentUser.role!=='admin')return;
  const col=$('admin-db-collection').value; const r=await DB.get(col,id); if(!r)return toast('السجل غير موجود','error');
  modal('تعديل سجل — '+(ADMIN_DB_COLLECTIONS[col]||col),`<div class="form-group"><label>JSON</label><textarea id="admin-db-json" rows="18" style="direction:ltr;text-align:left;font-family:monospace">${esc(JSON.stringify(r,null,2))}</textarea></div>`,`<button class="btn btn-outline" onclick="closeModal()">إلغاء</button><button class="btn btn-primary" onclick="window.adminDbSave('${esc(String(id))}')">حفظ التعديل</button>`);
};
window.adminDbSave=async oldId=>{
  try{
    if(!currentUser||currentUser.role!=='admin')throw new Error('غير مصرح');
    const col=$('admin-db-collection').value; const obj=JSON.parse($('admin-db-json').value);
    const kf=col==='settings'?'key':'id';
    if(!obj[kf])obj[kf]=oldId||DB.uid(col.slice(0,3));
    if(oldId&&String(obj[kf])!==String(oldId))throw new Error('لا تغيّر المعرف أثناء التعديل');
    await DB.put(col,obj); await DB.log(currentUser.id,'admin_db_save','حفظ سجل في '+col,{collection:col,id:obj[kf]}); closeModal(); toast('تم الحفظ في قاعدة البيانات المركزية'); await renderAdminDatabase();
  }catch(e){toast(e.message||'JSON غير صالح','error')}
};
window.adminDbDelete=async id=>{
  try{
    if(!currentUser||currentUser.role!=='admin')throw new Error('غير مصرح');
    const col=$('admin-db-collection').value;
    if(col==='users'){const u=await DB.get('users',id);if(u?.role==='admin'&&(await DB.all('users')).filter(x=>x.role==='admin'&&x.status==='active').length<=1)throw new Error('لا يمكن حذف آخر مدير فعال');}
    if(!confirm('هل تريد حذف هذا السجل نهائياً من قاعدة البيانات؟'))return;
    await DB.del(col,id);await DB.log(currentUser.id,'admin_db_delete','حذف سجل من '+col,{collection:col,id});toast('تم حذف السجل');await renderAdminDatabase();
  }catch(e){toast(e.message||'تعذر الحذف','error')}
};
function initAdminMap(){if(typeof L==='undefined'||adminMap)return;adminMap=L.map('admin-map-container').setView([30.2989,31.7414],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(adminMap);DB.all('users').then(users=>users.filter(x=>x.role==='courier'&&x.online).forEach(u=>{if(u.lat&&u.lng)L.marker([u.lat,u.lng]).addTo(adminMap).bindPopup(u.name)}));}
// إضافة إدارة المديرين للقائمة حتى لو لم تكن موجودة في HTML الأصلي
function injectAdminManagers(){const nav=document.querySelector('#admin-sidebar .sidebar-nav');if(nav&&!$('nav-admin-managers')){const b=document.createElement('button');b.id='nav-admin-managers';b.className='side-item';b.dataset.page='admin-managers';b.innerHTML='<i class="fas fa-user-shield"></i> إدارة المديرين';b.onclick=()=>go('admin-managers');nav.insertBefore(b,nav.querySelector('#admin-logout'));const s=document.createElement('section');s.id='admin-managers';s.className='page';s.innerHTML='<div class="page-header"><h2>إدارة المديرين</h2><button class="btn btn-primary" onclick="adminManagerUI()"><i class="fas fa-user-plus"></i> إنشاء حساب مدير</button></div><div id="admin-managers-table" class="table-responsive"></div>';$('admin-screen').querySelector('.admin-content').appendChild(s)}}

// ===== REALTIME + SUPPORT CHAT/CALL =====
let realtimeUnsubs=[], activeSupportThread=null, callState={pc:null,local:null,remote:null,thread:null};
function stopRealtime(){realtimeUnsubs.forEach(u=>{try{u()}catch(e){}});realtimeUnsubs=[];try{DB.stopAllListeners()}catch(e){}}
function threadIdFor(userId){return 'support_'+userId+'_admin'}
async function setupRealtime(){
  stopRealtime(); if(!currentUser)return;
  const rerender=()=>{ if(currentUser.role==='admin') { refresh(); if($('admin-ranking')?.classList.contains('active')) renderAdminRanking(); } else refresh(); renderSupportIfOpen(); };
  ['users','orders','zones','settings','notifications','ranking_rewards'].forEach(col=>realtimeUnsubs.push(DB.listen(col,()=>rerender(),()=>{})));
  realtimeUnsubs.push(DB.listen('messages',()=>renderSupportIfOpen(),()=>{}));
  realtimeUnsubs.push(DB.listen('support_presence',rows=>{window.__supportPresence=rows;updateSupportStatus()},()=>{}));
  realtimeUnsubs.push(DB.listen('call_requests',rows=>{window.__callRequests=rows;handleIncomingCallRequests(rows)},()=>{}));
  try{await DB.touchPresence(currentUser.id,true); if(currentUser.role==='admin') await DB.put('support_presence',{id:currentUser.id,role:'admin',online:true,callOpen:false,updatedAt:DB.now()});}catch(e){}
}
function updateSupportStatus(){
  const admins=(window.__supportPresence||[]).filter(x=>x.role==='admin'&&x.online); const online=admins.length>0;
  ['client','courier'].forEach(role=>{const st=$(role+'-admin-status'),dot=$(role+'-admin-status-dot'),btn=$(role+'-call-btn');if(st){st.textContent=online?'الإدارة متصلة الآن':'الإدارة غير متصلة حالياً';}if(dot)dot.className='status-dot '+(online?'online':'offline');if(btn)btn.disabled=!online;});
}
async function openSupport(role){go(role+'-chat');await renderSupportChat(currentUser.id);}
async function renderSupportChat(userId){
  const msgs=(await DB.all('messages')).filter(m=>m.threadId===threadIdFor(userId)).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));
  const box=$('client-chat-messages')||$('courier-chat-messages')||$('admin-chat-messages'); if(!box)return;
  box.innerHTML=msgs.length?msgs.map(m=>`<div class="chat-bubble ${m.senderId===currentUser.id?'mine':'theirs'}"><div>${esc(m.text)}</div><small>${fmtDate(m.createdAt)}</small></div>`).join(''):empty('ابدأ المحادثة مع الإدارة');
  box.scrollTop=box.scrollHeight;
}
async function sendSupportMessage(userId,textMsg){const t=String(textMsg||'').trim();if(!t)return;const tid=threadIdFor(userId);await DB.put('messages',{id:DB.uid('msg'),threadId:tid,senderId:currentUser.role==='admin'?currentUser.id:userId,recipientId:currentUser.role==='admin'?userId:null,text:t,createdAt:DB.now(),read:false});}
async function renderSupportIfOpen(){
 if(!currentUser)return;
 if(currentUser.role==='client'&&$('client-chat')?.classList.contains('active')) return renderSupportChat(currentUser.id);
 if(currentUser.role==='courier'&&$('courier-chat')?.classList.contains('active')) return renderSupportChat(currentUser.id);
 if(currentUser.role==='admin'&&$('admin-support')?.classList.contains('active')) return renderAdminSupport();
}
async function renderAdminSupport(){
 const users=(await DB.all('users')).filter(u=>u.role!=='admin'); const msgs=await DB.all('messages');
 const threads=users.map(u=>{const ms=msgs.filter(m=>m.threadId===threadIdFor(u.id));const last=ms.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0];return {u,last}}).sort((a,b)=>String(b.last?.createdAt||'').localeCompare(String(a.last?.createdAt||'')));
 const list=$('support-threads'); if(!list)return; list.innerHTML=threads.map(({u,last})=>`<button class="support-thread ${activeSupportThread===u.id?'active':''}" onclick="window.openAdminThread('${u.id}')"><i class="fas fa-user-circle"></i><span><b>${esc(u.name)}</b><small>${esc(last?.text||'لا توجد رسائل')}</small></span></button>`).join('')||empty('لا توجد محادثات');
 if(activeSupportThread){const u=await DB.get('users',activeSupportThread);if(u){$('admin-chat-header').innerHTML=`<i class="fas fa-user-circle"></i> ${esc(u.name)} <small>${u.phone||''}</small>`;const ms=msgs.filter(m=>m.threadId===threadIdFor(u.id)).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));$('admin-chat-messages').innerHTML=ms.length?ms.map(m=>`<div class="chat-bubble ${m.senderId===currentUser.id?'mine':'theirs'}"><div>${esc(m.text)}</div><small>${fmtDate(m.createdAt)}</small></div>`).join(''):empty('ابدأ المحادثة');const b=$('admin-chat-messages');b.scrollTop=b.scrollHeight;}}
}
window.openAdminThread=async id=>{activeSupportThread=id;go('admin-support');await renderAdminSupport()};
async function startCall(userId){
 const online=(window.__supportPresence||[]).some(x=>x.role==='admin'&&x.online); if(!online)return toast('الإدارة غير متصلة الآن','error');
 const open=(await DB.all('support_presence')).some(x=>x.role==='admin'&&x.online&&x.callOpen); if(!open)return toast('الإدارة غير متاحة للمكالمات حالياً','error');
 const id=DB.uid('call');await DB.put('call_requests',{id,threadId:threadIdFor(userId),userId,adminId:null,status:'ringing',createdAt:DB.now()});toast('تم طلب الاتصال من الإدارة');
}
async function handleIncomingCallRequests(rows){
 if(!currentUser)return;
 if(currentUser.role==='admin'){
   const req=rows.filter(r=>r.status==='ringing'&&(!r.adminId||r.adminId===currentUser.id));const latest=req.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0];
   if(!latest||window.__lastCallReq===latest.id)return;window.__lastCallReq=latest.id;const u=await DB.get('users',latest.userId);
   if(u&&confirm(`مكالمة واردة من ${u.name}. قبول الاتصال؟`)){await DB.put('call_requests',{...latest,status:'accepted',adminId:currentUser.id});await openWebCall(latest.userId,true)}else if(u){await DB.put('call_requests',{...latest,status:'declined',adminId:currentUser.id})}
 } else {
   const accepted=rows.filter(r=>r.userId===currentUser.id&&r.status==='accepted').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0];
   if(accepted&&window.__acceptedCall!==accepted.id){window.__acceptedCall=accepted.id;await openWebCall(accepted.adminId,false)}
 }
}
async function openWebCall(peerId,isAdmin){
 if(!window.RTCPeerConnection||!navigator.mediaDevices)return toast('الاتصال الصوتي غير مدعوم على هذا الجهاز','error');
 const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});callState.pc=pc;callState.thread=threadIdFor(peerId);callState.remote=new MediaStream();
 const audio=document.createElement('audio');audio.autoplay=true;audio.srcObject=callState.remote;audio.id='active-call-audio';document.body.appendChild(audio);
 const local=await navigator.mediaDevices.getUserMedia({audio:true});callState.local=local;local.getTracks().forEach(t=>pc.addTrack(t,local));pc.ontrack=e=>e.streams[0].getTracks().forEach(t=>callState.remote.addTrack(t));
 const signalId=DB.uid('sig');const unsub=DB.listen('call_signals',async rows=>{for(const x of rows.filter(x=>x.threadId===callState.thread&&x.to===currentUser.id&&!x.consumed)){try{if(x.type==='offer')await pc.setRemoteDescription(x.data);if(x.type==='answer')await pc.setRemoteDescription(x.data);if(x.type==='candidate')await pc.addIceCandidate(x.data);await DB.put('call_signals',{...x,consumed:true})}catch(e){}}});realtimeUnsubs.push(unsub);
 pc.onicecandidate=e=>{if(e.candidate)DB.put('call_signals',{id:DB.uid('sig'),threadId:callState.thread,to:peerId,from:currentUser.id,type:'candidate',data:e.candidate.toJSON(),consumed:false,createdAt:DB.now()})};
 if(isAdmin){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await DB.put('call_signals',{id:signalId,threadId:callState.thread,to:peerId,from:currentUser.id,type:'offer',data:{type:offer.type,sdp:offer.sdp},consumed:false,createdAt:DB.now()})}
 else { const offers=(await DB.all('call_signals')).filter(x=>x.threadId===callState.thread&&x.to===currentUser.id&&x.type==='offer'&&!x.consumed).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))); const offer=offers[0]; if(offer){await pc.setRemoteDescription(offer.data);await DB.put('call_signals',{...offer,consumed:true});const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await DB.put('call_signals',{id:DB.uid('sig'),threadId:callState.thread,to:peerId,from:currentUser.id,type:'answer',data:{type:answer.type,sdp:answer.sdp},consumed:false,createdAt:DB.now()})}}
 showCallOverlay(peerId);
}
function showCallOverlay(peerId){if($('call-overlay'))return;const d=document.createElement('div');d.id='call-overlay';d.className='call-overlay';d.innerHTML='<div class="call-card"><i class="fas fa-phone-volume call-icon"></i><h3>اتصال صوتي</h3><p>المكالمة متصلة</p><button class="btn btn-danger" onclick="window.endWebCall()"><i class="fas fa-phone-slash"></i> إنهاء الاتصال</button></div>';document.body.appendChild(d)}
window.endWebCall=async()=>{try{callState.local?.getTracks().forEach(t=>t.stop());callState.pc?.close()}catch(e){}callState={pc:null,local:null,remote:null,thread:null};$('active-call-audio')?.remove();$('call-overlay')?.remove()};
function wireSupportUI(){
 $('client-chat-btn')?.addEventListener('click',()=>openSupport('client'));$('courier-chat-btn')?.addEventListener('click',()=>openSupport('courier'));
 [['client','client'],['courier','courier']].forEach(([r])=>{const inp=$(r+'-chat-input'),send=$(r+'-chat-send'),call=$(r+'-call-btn');send?.addEventListener('click',async()=>{await sendSupportMessage(currentUser.id,inp.value);inp.value='';renderSupportChat(currentUser.id)});inp?.addEventListener('keydown',e=>{if(e.key==='Enter')send.click()});call?.addEventListener('click',()=>startCall(currentUser.id));});
 $('admin-chat-send')?.addEventListener('click',async()=>{if(!activeSupportThread)return;const inp=$('admin-chat-input');await sendSupportMessage(activeSupportThread,inp.value);inp.value='';renderAdminSupport()});$('admin-chat-input')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('admin-chat-send').click()});
 $('admin-call-open')?.addEventListener('change',async e=>{await DB.put('support_presence',{id:currentUser.id,role:'admin',online:true,callOpen:e.target.checked,updatedAt:DB.now()});toast(e.target.checked?'تم فتح استقبال المكالمات':'تم إغلاق استقبال المكالمات')});
}

window.addEventListener('DOMContentLoaded',async()=>{injectAdminManagers();await init()});window.go=go;window.closeModal=closeModal;window.adminManagerUI=adminManagerUI;window.adminDbRefresh=renderAdminDatabase;window.logout=logout;
})();
